#!/usr/bin/env ruby
require 'highline/import'

Dir["./app/**/*.rb"].each {|f| require f }
Dir["./lib/*.rb"].each {|f| require f }


menu_prompt =<<EOS
1. Add a Dr. Phil quote
2. Add a Tiger Mom quote
3. List all Dr. Phil quotes
4. List all Tiger Mom quotes
5. Exit
EOS

if ARGV.empty?
  SurveyController.new().quiz
elsif ARGV.size == 1 and ARGV[0] == "manage"
  loop do
    choose do |menu|
      menu.prompt = ""

      quotes_controller = QuotesController.new
      menu.choice('Add a Dr. Phil quote') do
        say(quotes_controller.add_phil)
        exit
      end
      menu.choice('Add a Tiger Mom quote') do
        say(quotes_controller.add_tiger)
        exit
      end
      menu.choice('List all Dr. Phil quotes') do
        say(quotes_controller.index_phil)
        exit
      end
      menu.choice('List all Tiger Mom quotes') do
        say(quotes_controller.index_tiger)
        exit
      end
      menu.choice('Exit') do
        say("Tomorrow's just a future yesterday.\n")
        exit
      end
    end
  end
else
  puts "[Help] Run as: ./inspirationals manage"
end



