#!/usr/bin/env ruby
require 'highline/import'

menu_prompt =<<EOS
1. Add a Dr. Phil quote
2. Add a Tiger Mom quote
3. List all Dr. Phil quotes
4. List all Tiger Mom quotes
5. Exit
EOS

if ARGV.size == 1 and ARGV[0] == "manage"
    choose do |menu|
      menu.prompt = ""

      menu.choice('Add a Dr. Phil quote') {say("")}
      menu.choice('Add a Tiger Mom quote') {say("")}
      menu.choice('List all Dr. Phil quotes') {say("No quotes by Dr. Phil. Please add one.\n")}
      menu.choice('List all Tiger Mom quotes') {say("No quotes by Tiger Mom. Please add one.\n")}
      menu.choice('Exit') { say("Tomorrow's just a future yesterday.\n")}
    end
else
  puts "[Help] Run as: ./inspirationals manage"
end


