#!/usr/bin/env ruby
require 'highline/import'

Dir["./app/**/*.rb"].each {|f| require f }
Dir["./lib/*.rb"].each {|f| require f }


menu_prompt =<<EOS
1. Add a Dr. Phil quote
2. Add a Tiger Mom quote
3. List all Dr. Phil quotes
4. List all Tiger Mom quotes
5. Exit
EOS

if ARGV.size == 1 and ARGV[0] == "manage"
  loop do  
  choose do |menu|
      menu.prompt = ""

      quotes_controller = QuotesController.new
      menu.choice('Add a Dr. Phil quote') do
        user_input = ask("Please type in your Dr. Phil quote.\n")
        response = quotes_controller.add(user_input)
        say("\"#{user_input}\" has been added.\n") unless user_input.nil?
      end
      menu.choice('Add a Tiger Mom quote') do
        user_input = ask("Please type in your Tiger Mom quote.\n")
        response = quotes_controller.add(user_input)
        say("\"#{user_input}\" has been added.\n") unless user_input.nil?
      end
      menu.choice('List all Dr. Phil quotes') do
        say(quotes_controller.index)
        exit
      end
      menu.choice('List all Tiger Mom quotes') do
        say(quotes_controller.index)
        exit
      end
      menu.choice('Exit') do
        say("Tomorrow's just a future yesterday.\n")
        exit
      end
    end
  end
else
  puts "[Help] Run as: ./inspirationals manage"
end



